name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test-release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      
      - name: Configure
        run: |
          if [ "${{ matrix.os }}" = "windows-2022" ]; then
            cmake --preset=release-with-tests -G "Visual Studio 17 2022"
          else
            cmake --preset=release-with-tests
          fi
        shell: bash
      
      - name: Build
        run: cmake --build --preset=release-with-tests
      
      - name: Test
        run: ctest --preset=release-with-tests

  build-and-test-debug:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      
      - name: Configure
        run: cmake --preset=debug
        shell: bash
      
      - name: Build
        run: cmake --build --preset=debug
      
      - name: Test
        run: ctest --preset=debug