name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
        build-type: [debug, release-with-tests]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      
      - name: Configure
        run: cmake --preset=${{ matrix.build-type }}
      
      - name: Build
        run: cmake --build --preset=${{ matrix.build-type }}
      
      - name: Test
        if: matrix.build-type == 'release-with-tests' || matrix.build-type == 'debug'
        run: ctest --preset=${{ matrix.build-type }}